# Generated by Django 3.1.7 on 2021-04-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasteApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codepost',
            name='post_number',
        ),
        migrations.AddField(
            model_name='codepost',
            name='post_content',
            field=models.CharField(default='0000000', max_length=200),
        ),
    ]
