# Generated by Django 3.1.7 on 2021-05-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasteApp', '0002_auto_20210413_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepost',
            name='title',
            field=models.CharField(default='0000000', max_length=200),
        ),
    ]
